# Generated by Django 4.1.4 on 2022-12-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codename',
            field=models.CharField(default='codename', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first_name', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last_name', max_length=254),
            preserve_default=False,
        ),
    ]
