# Generated by Django 4.1.4 on 2022-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0002_alter_user_codename_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('occured_date', models.DateField()),
                ('win', models.TextField()),
                ('win_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
