# Generated by Django 4.1.4 on 2022-12-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0003_user_codepen_user_github_user_linkedin_and_more'),
        ('InternalInterviewService', '0003_win'),
    ]

    operations = [
    ]
