# Generated by Django 4.1.4 on 2022-12-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0007_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='file',
            new_name='thank_you_letter_file',
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('job_listing', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='InternalInterviewService.targetcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('metric', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('date_to_complete', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.coverletter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.job')),
                ('questions', models.ManyToManyField(to='InternalInterviewService.question')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.resume')),
                ('starrs', models.ManyToManyField(to='InternalInterviewService.starrquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL)),
                ('wins', models.ManyToManyField(to='InternalInterviewService.win')),
            ],
        ),
        migrations.AddField(
            model_name='coverletter',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='InternalInterviewService.job'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='InternalInterviewService.job'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='InternalInterviewService.job'),
        ),
    ]
