# Generated by Django 4.1.4 on 2022-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0008_rename_file_interview_thank_you_letter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('IQ', 'Interview Questions'), ('CQ', 'Company Questions')], max_length=2),
        ),
    ]
