# Generated by Django 4.1.4 on 2022-12-31 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0010_shortpersonalpitch_longpersonalpitch_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        )
    ]
