# Generated by Django 4.1.4 on 2022-12-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0011_alter_job_notes_shortpersonalpitch_longpersonalpitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Dossier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
