# Generated by Django 4.1.5 on 2023-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0015_shortpersonalpitch_longpersonalpitch_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='win_picture',
            field=models.ImageField(blank=True, null=True, upload_to='win_picture'),
        ),
    ]
