# Generated by Django 4.1.4 on 2023-01-04 21:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('InternalInterviewService', '0019_alter_starrquestions_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
