# Generated by Django 4.1.4 on 2023-01-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0020_alter_dossier_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='coverletter'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='cover_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.coverletter'),
        ),
    ]
