# Generated by Django 4.1.4 on 2023-01-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0021_alter_coverletter_file_alter_dossier_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.coverletter'),
        ),
    ]
