# Generated by Django 4.1.4 on 2023-01-04 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0023_alter_dossier_cover_letter_alter_dossier_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='InternalInterviewService.coverletter'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='InternalInterviewService.question'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='starrs',
            field=models.ManyToManyField(blank=True, null=True, to='InternalInterviewService.starrquestions'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='wins',
            field=models.ManyToManyField(blank=True, null=True, to='InternalInterviewService.win'),
        ),
    ]
