# Generated by Django 4.1.5 on 2023-01-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0026_alter_question_question_type_alter_resume_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='win_picture',
            field=models.ImageField(blank=True, null=True, upload_to='win_picture'),
        ),
    ]
