# Generated by Django 4.1.4 on 2023-01-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0026_alter_question_question_type_alter_resume_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemquestion',
            name='user',
        ),
    ]
