# Generated by Django 4.1.5 on 2023-01-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0027_alter_win_win_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letter_file'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file'),
        ),
    ]
