# Generated by Django 4.1.5 on 2023-01-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0029_alter_coverletter_file_alter_resume_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='file',
            new_name='cover_letter_file',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.RemoveField(
            model_name='systemquestion',
            name='user',
        ),
    ]
