# Generated by Django 4.1.5 on 2023-01-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0030_rename_file_coverletter_cover_letter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='InternalInterviewService.job'),
        ),
    ]
