# Generated by Django 4.1.5 on 2023-01-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0031_alter_coverletter_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemquestion',
            name='user',
        ),
    ]
