# Generated by Django 4.1.5 on 2023-01-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0032_remove_systemquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longpersonalpitch',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='shortpersonalpitch',
            name='draft',
        ),
    ]
