# Generated by Django 4.1.5 on 2023-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0033_remove_longpersonalpitch_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longpersonalpitch',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortpersonalpitch',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
