# Generated by Django 4.1.5 on 2023-01-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0034_longpersonalpitch_draft_shortpersonalpitch_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemquestion',
            name='user',
        ),
    ]
