# Generated by Django 4.1.5 on 2023-01-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0034_longpersonalpitch_draft_shortpersonalpitch_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Dossier',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InternalInterviewService.dossier'),
        ),
    ]
