# Generated by Django 4.1.5 on 2023-01-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0034_longpersonalpitch_draft_shortpersonalpitch_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
