# Generated by Django 4.1.5 on 2023-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalInterviewService', '0035_remove_coverletter_job_remove_dossier_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='longpersonalpitch',
            name='pitch',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='longpersonalpitch',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shortpersonalpitch',
            name='pitch',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='shortpersonalpitch',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='action',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='question',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='reflection',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='result',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='situation',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='starrquestions',
            name='task',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='systemquestion',
            name='question',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_pitch',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='win',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
